version: "2"

run:
  go: "1.24"
  modules-download-mode: readonly
  issues-exit-code: 1
  tests: true
  timeout: 5m

linters:
  default: none
  enable:
    - bodyclose
    - errcheck
    - errname
    - errorlint
    - goconst
    - gocritic
    - gocyclo
    - govet
    - ineffassign
    - misspell
    - nilerr
    - nilnil
    - staticcheck
    - unconvert
    - unused
    - whitespace

  settings:
    errcheck:
      check-type-assertions: true
      check-blank: true
      exclude-functions:
        - fmt.Print
        - fmt.Println
        - fmt.Printf
        - (*os.File).Close
        - (*github.com/spf13/pflag.FlagSet).GetBool
        - (*github.com/spf13/pflag.FlagSet).GetString
        - (*github.com/spf13/pflag.FlagSet).GetStringSlice
        - (*github.com/spf13/pflag.FlagSet).GetInt

    errorlint:
      errorf: true
      asserts: true
      comparison: true

    goconst:
      min-len: 8
      min-occurrences: 3

    gocritic:
      disabled-checks:
        - hugeParam
        - rangeValCopy
        - appendAssign
      enabled-tags:
        - diagnostic
        - style
        - performance

    gocyclo:
      min-complexity: 25

    govet:
      disable:
        - fieldalignment
        - shadow
      enable-all: true

    misspell:
      locale: US

    staticcheck:
      checks:
        - all

  exclusions:
    presets:
      - std-error-handling
      - common-false-positives
    rules:
      # Test files - allow unchecked errors and other style issues in tests
      - path: _test\.go
        linters:
          - errcheck
          - gocyclo
          - goconst
          - ineffassign
          - nilnil
          - nilerr
          - gocritic
          - govet
          - staticcheck

      # Explicitly ignored errors (fire and forget pattern with underscore)
      - text: "Error return value of.*is not checked"
        source: "_ :?="
        linters:
          - errcheck

      # Intentional ignored errors in cache manager for best-effort operations
      - path: cache/manager\.go
        text: "Error return value of"
        linters:
          - errcheck

      # Defer Close() is intentional (cleanup pattern)
      - text: "Error return value of.*Close.*is not checked"
        linters:
          - errcheck

      # goconst for short literal strings in specific files
      - path: (quality|tools/rust_tools)\.go
        linters:
          - goconst

      # Storage temp file extension constant
      - path: cache/storage\.go
        linters:
          - goconst

      # Benchmark results unused struct fields
      - path: bench_test\.go
        linters:
          - govet

      # Package comments not required for all packages
      - text: "ST1000"
        linters:
          - staticcheck

      # MessageId is from external JSON format (pylint)
      - text: "ST1003.*MessageId"
        linters:
          - staticcheck

      # Intentional nil return after error in WalkDir callback
      - path: cache/storage\.go
        text: "error is not nil.*but it returns nil"
        linters:
          - nilerr

issues:
  max-issues-per-linter: 50
  max-same-issues: 10
  new: false

  exclude-dirs:
    - vendor
    - .git
    - tmp
    - build
