run:
  go: "1.24"
  modules-download-mode: readonly
  issues-exit-code: 1
  tests: true
  timeout: 5m

linters:
  disable-all: true
  enable:
    - bodyclose
    - errcheck
    - errname
    - errorlint
    - goconst
    - gocritic
    - gocyclo
    - govet
    - ineffassign
    - misspell
    - nilerr
    - nilnil
    - staticcheck
    - unconvert
    - unused
    - whitespace

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true
    exclude-functions:
      - fmt.Print
      - fmt.Println
      - fmt.Printf
      - (*os.File).Close
      - (*github.com/spf13/pflag.FlagSet).GetBool
      - (*github.com/spf13/pflag.FlagSet).GetString
      - (*github.com/spf13/pflag.FlagSet).GetStringSlice
      - (*github.com/spf13/pflag.FlagSet).GetInt

  errorlint:
    errorf: true
    asserts: true
    comparison: true

  exhaustive:
    default-signifies-exhaustive: false

  gocognit:
    min-complexity: 30

  goconst:
    min-len: 8  # Ignore short strings (emoji and basic strings)
    min-occurrences: 3

  gocritic:
    disabled-checks:
      - hugeParam
      - rangeValCopy
    enabled-tags:
      - diagnostic
      - style
      - performance

  gocyclo:
    min-complexity: 25

  gosec:
    severity: high
    confidence: medium

  govet:
    disable:
      - fieldalignment
      - shadow
    enable-all: true

  lll:
    line-length: 180

  misspell:
    locale: US

  staticcheck:
    checks:
      - all

  unparam:
    check-exported: false

issues:
  max-issues-per-linter: 50
  max-same-issues: 10
  exclude-use-default: false
  new: false

  exclude-rules:
    # Test files
    - linters:
        - errcheck
        - gocyclo
      path: _test\.go

    # Defer Close() is intentional (cleanup pattern)
    - linters:
        - errcheck
      text: "Error return value of.*Close.*is not checked"

    # goconst for short literal strings
    - linters:
        - goconst
      path: (quality|tools/rust_tools)\.go

  exclude-dirs:
    - vendor
    - .git
    - tmp
    - build
