name: Feature Request
description: Suggest a new feature or enhancement
title: "[Feature]: "
labels: ["enhancement", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature!

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: Is your feature request related to a problem? Please describe.
      placeholder: I'm always frustrated when...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like
      placeholder: I would like gzq to...
    validations:
      required: true

  - type: dropdown
    id: category
    attributes:
      label: Feature Category
      description: What type of feature is this?
      options:
        - New Quality Tool Support
        - New Language Support
        - CLI Enhancement
        - Configuration Option
        - Performance Improvement
        - Documentation
        - Other
    validations:
      required: true

  - type: textarea
    id: use-case
    attributes:
      label: Use Case
      description: Describe your use case and how this feature would help
      placeholder: |
        In my project, I need to...
        This feature would help by...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Describe any alternative solutions or features you've considered
      placeholder: I've tried... but it doesn't work because...

  - type: textarea
    id: examples
    attributes:
      label: Example Usage
      description: Show how you would use this feature
      placeholder: |
        ```bash
        gzq run --new-flag
        ```
      render: shell

  - type: dropdown
    id: contribution
    attributes:
      label: Would you like to contribute this feature?
      options:
        - "Yes, I can implement this"
        - "Yes, with guidance"
        - "No, but I can test it"
        - "No"

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, or references

  - type: checkboxes
    id: terms
    attributes:
      label: Checklist
      description: Please confirm the following
      options:
        - label: I have searched existing issues to ensure this is not a duplicate
          required: true
        - label: This feature aligns with the project's goals (multi-language quality tool orchestration)
          required: true
